packages:
  - '*'
  - core-libs/*
  - scaffolding/default
  - cli
  - server
  - core/*
catalog:
  vite: ^6.3.5
onlyBuiltDependencies:
  - '@tailwindcss/vite-plugin'
  - bsdiff-node
  - esbuild
  - vite
