name: CI

on:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install deps
        run: pnpm install

      - name: Sync versions
        run: node sync-versions.mjs

      - name: Build
        run: pnpm build

      - name: Publish (on tag only)
        if: startsWith(github.ref, 'refs/tags/v')
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

